/**
 * Regenerates `src/lib/subregions.js` from the source's own region tree.
 *
 * The alert feed lists every district and community under alert as a flat
 * entry with no parent, so the extension needs to know which oblast each one
 * belongs to. That tree changes only when the country's administrative map
 * does, so it ships with the extension instead of costing the source a second
 * request on every tick.
 *
 *   node tools/subregions.mjs && npx prettier --write src/lib/subregions.js
 */

import { writeFile } from 'node:fs/promises';

import { REGIONS } from '../src/lib/regions.js';

const TREE_URL = 'https://siren.pp.ua/api/v3/regions';
const OUTPUT = 'src/lib/subregions.js';

/**
 * Cities the tree lists at the top level, beside their oblasts rather than
 * inside them. An alert there is still an alert in that oblast.
 */
const DETACHED = {
  1293: 'kharkiv',
  564: 'zaporizhzhia',
};

const descendants = (node) =>
  (node.regionChildIds ?? []).flatMap((child) => [
    Number(child.regionId),
    ...descendants(child),
  ]);

const run = async () => {
  const response = await fetch(TREE_URL);
  if (!response.ok) throw new Error(`regions → HTTP ${response.status}`);
  const { states } = await response.json();

  const lines = [];
  for (const region of REGIONS) {
    const node = states.find((state) => state.regionId === region.sourceId);
    if (!node) throw new Error(`The tree has no region ${region.sourceId}`);
    const detached = Object.keys(DETACHED)
      .filter((id) => DETACHED[id] === region.id)
      .map(Number);
    const ids = [...descendants(node), ...detached].sort((a, b) => a - b);
    lines.push(`  '${region.id}': [${ids.join(', ')}],`);
  }

  const source = `/**
 * Every district and community the alert source knows, by the oblast it lies
 * in. Generated by \`node tools/subregions.mjs\` — do not edit by hand.
 */
export const SUBREGIONS = {
${lines.join('\n')}
};
`;
  await writeFile(OUTPUT, source);
  console.log(`Wrote ${OUTPUT}`);
};

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
